### ISSUE TITLE
Label n° 7 vide

### ISSUE THREAD

**Issue by NasssDev** [emilesabatier/plan-comptable-JSON#1]
Bonjour je voulais faire remarquer que le label da la classe 7 n'a pas de valeur je pense que ça devrait être le label "produit, faites moi savoir si c'est correct, je n'ai pas nonplus eu connaissance de la classe 8 on ne m'a pas demandé de l'intégrer je me demande si je dois le faire

**Comment by 656d696c65** [comment]
Bonjour,

Je vous remercie, c'est une erreur de ma part. Il s'agit bien du compte de "Produits". 

Concernant la classe 8, je l'ai également ajoutée car elle est mentionnnée dans le [règlement ANC](https://www.anc.gouv.fr/files/live/sites/anc/files/contributed/ANC/1_Normes_fran%C3%A7aises/Reglements/Recueils/PCG_Janvier2023/PCG_1er-janvier-2023.pdf).

Notez également qu'il s'agit de la version 2023. Je publierai la version 2024 au courant du mois de mars.

**Comment by NasssDev** [comment]
Magnifique merci beaucoup, voila qui nous facilitera bien, pour le moment j'intégrerais celui-ci (à des fins de test).

Bon courage  !
